{
 "title": "Scaleway Consumption Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scaleway Total Consumption - Current Month",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Scaleway Total Consumption Current Month",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "scaleway_consumption_total_projects ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Scaleway Total Consumption Current Month - by Project",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "euros" } },
   "targets": [
    {
     "expr": "scaleway_consumption_total_projects ",
     "legendFormat": "Total"
    },
    { "expr": "scaleway_consumption_project", "legendFormat": "{{project_name}}" }
   ]
  },
  {
   "title": "Scaleway Last 12 Months Consumption - by Project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Last 12 Months consumption - scw-project1",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaleway_consumption_month{project_name=\"scw-project1\"}",
     "legendFormat": "{{month}}"
    }
   ]
  },
  {
   "title": "Last 12 Months consumption - scw-project2-ha",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaleway_consumption_month{project_name=\"scw-project2-ha\"}",
     "legendFormat": "{{month}}"
    }
   ]
  },
  {
   "title": "Last 12 Months consumption - scw-project2",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaleway_consumption_month{project_name=\"scw-project2\"}",
     "legendFormat": "{{month}}"
    }
   ]
  },
  {
   "title": "Last 12 Months consumption - scw-project3",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaleway_consumption_month{project_name=\"scw-project3\"}",
     "legendFormat": "{{month}}"
    }
   ]
  },
  {
   "title": "Scaleway Category Consumption Current Month - By Project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Scaleway Category Consumption Current Month - scw-project1",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "euros" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaleway_consumption_category{project_name=\"scw-project1\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Scaleway Category Consumption Current Month - scw-project2",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "euros" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaleway_consumption_category{project_name=\"scw-project2\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Scaleway Category Consumption Current Month - scw-project3",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "euros" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaleway_consumption_category{project_name=\"scw-project3\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Scaleway Category Consumption Current Month - scw-project2-ha",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "euros" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaleway_consumption_category{project_name=\"scw-project2-ha\"}",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}